# Generated by Django 4.1.2 on 2022-10-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('Email', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('roll', models.CharField(max_length=150)),
            ],
        ),
    ]
