# Generated by Django 4.1.2 on 2022-10-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo1app', '0002_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userform',
            old_name='roll',
            new_name='role',
        ),
    ]
