# Generated by Django 4.1.2 on 2022-10-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo1app', '0003_rename_roll_userform_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
